# Below application is creates DataFrame using Pandas and writhe the contents of that
# DataFrame in xlsx file using ExcelWriter.

import pandas as pd

data = [{'name':'ppa','duration':3,'fees':10500},{'name':'angular','duration':3,'fees':11500},{'name':'python','duration':3,'fees':12500}]
df = pd.DataFrame(data)
print(df)

writer =  pd.ExcelWriter("filegenrate.xlsx",engine='xlsxwriter')

df.to_excel(writer,sheet_name='sheet1')
writer.save()

# Excel file which is generated by above application 
